spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://***/pgnc
    username: ***
    password: ***
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 0
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
        slf4j:
          enabled: true
          connection-log-enabled: true
      stat-view-servlet:
        enabled: true
        login-username: pgnc
        login-password: pgnc
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      aop-patterns: team.hld.service.*
